CREATE OR REPLACE DATABASE NYC_TAXI;

CREATE OR REPLACE SCHEMA NYC_TAXI.BRONZE;
CREATE OR REPLACE SCHEMA NYC_TAXI.SILVER;
CREATE OR REPLACE SCHEMA NYC_TAXI.GOLD;

CREATE OR REPLACE WAREHOUSE WH_NYC_TAXI
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE WH_NYC_TAXI;
USE DATABASE NYC_TAXI;

CREATE OR REPLACE TABLE SILVER.TAXI_TRIPS_CLEAN (
  trip_id STRING,
  vendor_id STRING,
  pickup_datetime TIMESTAMP_NTZ,
  dropoff_datetime TIMESTAMP_NTZ,
  passenger_count INTEGER,
  trip_distance FLOAT,
  pu_location_id INTEGER,
  do_location_id INTEGER,
  fare_amount FLOAT,
  tip_amount FLOAT,
  total_amount FLOAT,
  source_file STRING,
  ingested_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE GOLD.DAILY_METRICS (
  service_date DATE,
  trips INTEGER,
  total_fare FLOAT,
  total_tip FLOAT,
  avg_distance FLOAT,
  avg_total_amount FLOAT,
  updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
